services:
  backend:
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - 3000:3000
  frontend:
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - 4200:4200